version: '3'
# Please do not use <tab> when edit 
# Basic bundle of demo applications

services:

# Example containers with source codes

# nodejs demo app, based on nodejs express https://expressjs.com/ 
# mounted to local disk ./nodejs_app

  nodejs-docker-sample-webapp: 
    container_name: nodehello
    image: "node:latest"
    tty: true # Enables debugging capabilities when attached to this container.
    # user: "node"
    working_dir: /home/node/app
    volumes:
      - ./nodejs_app:/home/node/app
    ports:
      - "3000:3000" # node express default webpage localhost:3000
    command: sh -c "npm start "
# logging guide https://docs.docker.com/compose/compose-file/compose-file-v2/#logging  
    logging:
      driver: "json-file"
    networks:
      hackstack:
        aliases: 
         - nodehello
 
# python demo app
# mounted to local disk ./python-docker-sample-webapp/webapp 
  python-docker-sample-webapp:
    container_name: pythonhello
    build:
      context: python-docker-sample-webapp/    
    working_dir: /opt/webapp
    volumes:
      - ./python-docker-sample-webapp/webapp:/opt/webapp
    ports:
    - "5555:5000" # <exposed port>:<internal docker port>
    logging:
      driver: "json-file"
    networks:
      hackstack:
        aliases: 
         - pythonhello

# spring boot demo app
  spring-boot-sample:    
    container_name: springhello
    build:
      context: spring-boot-demo/
    #image: garystafford/hello-world:latest
    ports:
      - "8099:8080/tcp" # optional
    command: "java \
      -Dspring.profiles.active=dev \
      -Djava.security.egd=file:/dev/./urandom \
      -jar hello/hello-world.jar"
    logging:
       driver: json-file
    networks:
      hackstack:
        aliases: 
         - springhello

# go demo app
  go-sample: 
    container_name: gohello
    build:
      context: go-docker-demo/
    ports:
     - "8077:8080/tcp" # optional
    logging:
      driver: json-file
    networks:
      hackstack:
        aliases: 
         - gohello

networks:
  hackstack:
    driver: bridge
